contributions/catalog/controllers/contribute.py
#  Copyright 2021 Board of Trustees of the University of Illinois.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import json
import logging
import traceback
import requests
import datetime

from flask import (
    Blueprint, render_template, request, session, redirect, url_for
)
from requests_oauthlib import OAuth2Session
from .auth import login_required
from controllers.config import Config as cfg
from utils import jsonutil
from utils import adminutil
from utils import requestutil
import models.contribution_utilities as cont_util

import os

bp = Blueprint('contribute', __name__, url_prefix=cfg.URL_PREFIX)


@bp.route('/', methods=['GET', 'POST'])
def home():
    show_sel = request.args.get('show')
    user = None
    token = None
    is_logged_in = False
    cap_json = []
    tal_json = []

    if 'GIT_TAG' in os.environ:
        git_tag=os.environ['GIT_TAG']
    else:
        git_tag=''
    if 'GIT_SHA' in os.environ:
        git_sha=os.environ['GIT_SHA']
    else:
        git_sha=''

    try:
        # create error to see if the user is logged in or now
        # TODO this should be changed to better way
        if (session["name"] == ""):
            is_logged_in = True
        else:
            is_logged_in = True
        user = session["name"]
        token = session['oauth_token']['access_token']
    except:
        is_logged_in = False

    if (is_logged_in):
        # query with auth
        headers = requestutil.get_header_using_session(session)
        result = requestutil.request_contributions(headers)
        if show_sel == "capability":
            # create the json for only capability
            cap_json = jsonutil.create_capability_json_from_contribution_json(result.json())
        elif show_sel == "talent":
            # create the json for only talent
            tal_json = jsonutil.create_talent_json_from_contribution_json(result.json())
        else:
            # create the json for only capability and talent
            cap_json = jsonutil.create_capability_json_from_contribution_json(result.json())
            tal_json = jsonutil.create_talent_json_from_contribution_json(result.json())

        return render_template('contribute/home.html', git_tag=git_tag, git_sha=git_sha, cap_json=cap_json, tal_json=tal_json,
                               show_sel=show_sel, user=user)
    else:
        # query only published ones
        headers = requestutil.get_header_using_api_key()
        result = requestutil.request_contributions(headers)
        if show_sel == "capability":
            # create the json for only capability
            cap_json = jsonutil.create_capability_json_from_contribution_json(result.json())
        elif show_sel == "talent":
            # create the json for only talent
            tal_json = jsonutil.create_talent_json_from_contribution_json(result.json())
        else:
            # create the json for only capability and talent
            cap_json = jsonutil.create_capability_json_from_contribution_json(result.json())
            tal_json = jsonutil.create_talent_json_from_contribution_json(result.json())

        return render_template('contribute/home.html', git_tag=git_tag, git_sha=git_sha, cap_json=cap_json, tal_json=tal_json, show_sel=show_sel)

    # print("homepage.")
    # if request.method == 'POST' and request.validate_on_submit():
    #     result = request.form.to_dict(flat=False)
    # if "name" in session:
    #     return render_template('contribute/home.html', user=session["name"], token=session['oauth_token']['access_token'])
    # else:
    #     return render_template('contribute/home.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    """Step 1: Get the user identify for authentication.
    """
    # print("Step 1: User Authorization")
    github = OAuth2Session(cfg.GITHUB_CLIENT_ID)
    authorization_url, state = github.authorization_url(cfg.AUTHORIZATION_BASE_URL)

    # State is used to prevent CSRF.
    session['oauth_state'] = state
    return redirect(authorization_url)


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('.home'))


@bp.route('/results', methods=['POST', 'GET'])
@login_required
def result():
    if request.method == 'POST':
        # result = request.form
        result = request.form.to_dict()
        query = result['search']
        search(query)
        return render_template("contribute/results.html", user=session["name"],  token=session['oauth_token']['access_token'], result=result)

@bp.route('/contributions/<contribution_id>', methods=['GET'])
def contribution_details(contribution_id):
    # check if the user is logged in
    is_logged_in = False

    try:
        # create error to see if the use is logged in or now
        # TODO this should be changed to better way
        if (session["name"] == ""):
            is_logged_in = True
        else:
            is_logged_in = True
    except:
        is_logged_in = False

    is_editor = False
    is_reviewer = False
    name = ""

    if (is_logged_in):
        # check to see if the logged in user is an editable user for creating edit button
        username = session["username"]
        name = session["name"]
        headers = requestutil.get_header_using_session(session)
        # check if the user is reviewer by requesting to endpoint
        is_reviewer = adminutil.check_if_reviewer(username, headers)
        result = requests.get(cfg.CONTRIBUTION_BUILDING_BLOCK_URL + "/" + str(contribution_id),
                              headers=headers)
        if result.status_code != 200:
            err_json = parse_response_error(result)
            logging.error("Contribution GET " + json.dumps(err_json))
            msg = "Error: " + err_json['reason']
            return render_template('contribute/error.html', error_msg=msg)

        the_json_res = result.json()
        # check if the logged in user is the editor
        is_superuser = adminutil.check_if_superuser(username)
        if is_superuser:
            is_editor = True
        elif username in the_json_res["contributionAdmins"]:
            is_editor = True

    else:
        headers = requestutil.get_header_using_api_key()
        result = requests.get(cfg.CONTRIBUTION_BUILDING_BLOCK_URL + "/" + str(contribution_id),
                              headers=headers)
        the_json_res = result.json()
        if result.status_code != 200:
            err_json = parse_response_error(result)
            logging.error("Contribution GET " + json.dumps(err_json))
            msg = "Error: " + err_json['reason']
            return render_template('contribute/error.html', error_msg=msg)

    return render_template("contribute/contribution_details.html", is_reviewer=is_reviewer, is_editable=is_editor,
                            post=the_json_res, user=name)

@bp.route('/contributions/<contribution_id>/edit', methods=['GET', 'POST'])
@login_required
def contribution_edit(contribution_id):
    if request.method == 'POST':
        is_put = False
        contribution_id = None
        result = request.form.to_dict(flat=False)

        # check if it is PUT
        try:
            contribution_id = result["contribution_id"][0]
            is_put = True
        except:
            s = "There is a error in edit. The method is not an edit."
            return render_template('contribute/error.html', error_msg=s)

        if is_put:
            contribution = cont_util.to_contribution(result)
            contribution = jsonutil.add_contribution_admins(contribution, is_edit=True)
            # remove id from json_data
            del contribution["id"]
            json_contribution = json.dumps(contribution, indent=4)
            response, s = put_contribution(json_contribution, contribution_id)

            if response:
                if "name" in session:
                    return redirect(url_for('contribute.contribution_details', contribution_id=contribution_id))
                else:
                    return render_template('contribute/submitted.html')
            elif not response:
                if "name" in session:
                    return render_template('contribute/error.html', user=session["name"],
                                           token=session['oauth_token']['access_token'], error_msg=s)
                else:
                    return render_template('contribute/error.html', error_msg=s)
    else:
        the_json_res = get_contribution(contribution_id)
        # check if the user is editable then set the is_editable
        is_editable = False
        is_reviewer = False
        username = session["username"]
        headers = requestutil.get_header_using_session(session)

        # check if the user is in contribution's admins
        if username in the_json_res["contributionAdmins"]:
            is_editable = True

        # check if the user is a reviewer
        is_reviewer = adminutil.check_if_reviewer(username, headers)

        if is_reviewer:
            is_editable = True

        # get required building block list to create required building block list
        building_blocks_list = requestutil.request_buildingblocks(requestutil.get_header_using_api_key())

        # get capability list to create required capability list
        required_capability_list = requestutil.request_required_capability_list(headers)

        if is_editable:

contributions/catalog/controllers/contributions.py
import json
import traceback

# from app import app
import requests
from controllers.config import Config
from flask import (
    abort, Blueprint, render_template, request, jsonify
)
from models.contribution_utilities import to_contribution

bp = Blueprint('contributions', __name__, url_prefix='/contributions')


@bp.route('/', methods=['GET', 'POST'])
def home():
    print("homepage.")
    if request.method == 'POST' and request.validate_on_submit():
        print("searching...")
        result = request.form.to_dict(flat=False)
        print(result)
        # search(result)
    return render_template('contributions/home.html')


@bp.route('/results', methods=['POST', 'GET'])
def result():
    if request.method == 'POST':
        # result = request.form
        print("searching...")
        result = request.form.to_dict()
        print(result)
        query = result['search']
        search(query)
        return render_template("contributions/results.html", result=result)

@bp.route('/catalog/auth/callback', methods=['GET'])
def callback():
    if request.method == 'GET':
        print(request)
        code = None
        state = None
        try:
            code = request.args['code']
        except Exception:
            pass
        try:
            state = request.args['state']
        except Exception:
            pass
    print("test")

@bp.route('/create', methods=['GET', "POST"])
def create():
    if request.method == 'POST':
        result = request.form.to_dict(flat=False)
        # result = dict((key, request.form.getlist(key) if len(request.form.getlist(key)) > 1 else request.form.getlist(key)[0]) for key in request.form.keys())

        contribution = to_contribution(result)
        # print(contribution)
        json_contribution = json.dumps(contribution, indent=4)
        print(json_contribution)
        response,s = post(json_contribution)
        if response:
            return render_template('contributions/submitted.html')
        elif not response:
            return render_template('contributions/error.html', error_msg=s)
    return render_template('contributions/contributions.html')

@bp.errorhandler(404)
def page_not_found(e):
    # note that we set the 404 status explicitly
    return render_template('contributions/submitted.html')

@bp.route('/submitted', methods=['GET', 'POST'])
def submitted():
    return render_template('contributions/submitted.html')


#

# @app.errorhandler(Exception)
# def handle_exception(e):
#     # pass through HTTP errors
#     if isinstance(e, HTTPException):
#         return e
#     # now you're handling non-HTTP exceptions only
#     return render_template("500_error.html", e=e), 500

@bp.route('/results')
def search_results(search):
    return render_template('results.html', results=results)


# post a json_data in a http request
def post(json_data):
    headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + Config.AUTHENTICATION_TOKEN
    }
    try:
        # Setting up post request
        result = requests.post(Config.CONTRIBUTION_BUILDING_BLOCK_URL,
                               headers=headers,
                               data=json_data)

        if result.status_code != 200:
            print("post method fails".format(json_data))
            print("with error code:", result.status_code)
            return False, str("post method fails with error: ")+str(result.status_code)
        else:
            print("posted ok.".format(json_data))
            return True, str("post success!")

    except Exception:
        traceback.print_exc()
        var = traceback.format_exc()
        return False, var


# post a json_data in a http request
def search(input_data):
    headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + Config.AUTHENTICATION_TOKEN
    }

    try:
        # Setting up post request
        if not input_data or len(input_data) == 0:
            result = requests.get(Config.CONTRIBUTION_BUILDING_BLOCK_URL + "/",
                                  headers=headers)
        else:
            result = requests.get(Config.CONTRIBUTION_BUILDING_BLOCK_URL + "/" + str(input_data),
                                  headers=headers)

        if result.status_code != 200:
            print("post method fails".format(input_data))
            print("with error code:", result.status_code)
            return False
        else:
            print("posted ok.".format(input_data))
            return True

    except Exception:
        # traceback.print_exc()
        return False

contributions/catalog/templates/contribute/home.html
<!DOCTYPE html>
<html>
<head>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="{{ url_for('static', filename='css/filter.css') }}" rel="stylesheet">

</head>
<body>


<style>

.navbar {
  overflow: hidden;
  background-color: #2a4b45;
  position: fixed;
  top: 0;
  width: 100%;
}

.navbar a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.navbar a:hover {
  background: #4c4c4c;
  color: white;
}

.navbar a.act {
  background-color: #88aeaf;
  color: white;
}

.main {
  padding: 30px;
  margin-top: 90px;
  height: 1500px;
}

/* Center website */
.main {
  max-width: 1000px;
  margin: auto;
}


/* Center website */
.main {
  max-width: 1000px;
  margin: auto;
}

h1 {
  font-size: 50px;
  word-break: break-all;
}

.row {
  margin: 10px -16px;
}

/* Add padding BETWEEN each column */
.row,
.row > .column {
  padding: 10px;
}

/* Create three equal columns that floats next to each other */
.column {
  float: left;
  width: 33.33%;
  display: none; /* Hide all elements by default */
}

/* Clear floats after rows */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Content */
.content {
  background-color: white;
  padding: 10px;
}

/* The "show" class is added to the filtered elements */
.show {
  display: block;
}

/* Style the buttons */
.btn {
  border: none;
  outline: none;
  padding: 12px 16px;
  background-color: white;
  cursor: pointer;
}

.btn:hover {
  background-color: #ddd;
  color: white;
}

.btn.active {
  background-color: #666;
  color: white;
}




</style>

<div class="navbar" id="myTopnav">
    <a href="{{ url_for('contribute.home') }}">Contribution Catalog</a>
    <a href="{{ url_for('contribute.create') }}">Submit</a>
</div>

<!-- MAIN (Center website) -->
<div class="main">
    <h1></h1>
    <h1>Contribution Catalog / Packager</h1>
    <!--<hr>-->

    <div id="myBtnContainer">
        <button class="btn active" onclick="filterSelection('all')"> Show all</button>
        <button class="btn" onclick="filterSelection('capability')"> Capability</button>
        <button class="btn" onclick="filterSelection('talent')"> Talent</button>
    </div>

    <div class="row">
        <div class="column capability">
            <div class="content">
                <img src="" style="width:100%">
                <h4>capability</h4>
                <p>description..</p>
                <span class="label label-default">App Config</span>
            </div>
        </div>
        <div class="column capability">
            <div class="content">
                <img src="" style="width:100%">
                <h4>capability</h4>
                <p>description..</p>
                <span class="label label-default">Profile</span>
            </div>
        </div>
        <div class="column capability">
            <div class="content">
                <img src="" style="width:100%">
                <h4>capability</h4>
                <p>description..</p>
                <span class="label label-default">Login</span>
            </div>
        </div>

        <div class="column talent">
            <div class="content">
                <img src="" style="width:100%">
                <h4>talent</h4>
                <p>description..</p>
                <span class="label label-default">Login</span>
            </div>
        </div>
        <div class="column talent">
            <div class="content">
                <img src="" style="width:100%">
                <h4>talent</h4>
                <p>description..</p>
                <span class="label label-default">Auth</span>
            </div>
        </div>
        <div class="column talent">
            <div class="content">
                <img src="" style="width:100%">
                <h4>talent</h4>
                <p>description..</p>
                <span class="label label-default">Events</span>
            </div>
        </div>

        <!-- END GRID -->
    </div>

    <!-- END MAIN -->
</div>

<script>
filterSelection("all")
function filterSelection(c) {
  var x, i;
  x = document.getElementsByClassName("column");
  if (c == "all") c = "";
  for (i = 0; i < x.length; i++) {
    w3RemoveClass(x[i], "show");
    if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
  }
}

function w3AddClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    if (arr1.indexOf(arr2[i]) == -1) {element.className += " " + arr2[i];}
  }
}

function w3RemoveClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    while (arr1.indexOf(arr2[i]) > -1) {
      arr1.splice(arr1.indexOf(arr2[i]), 1);
    }
  }
  element.className = arr1.join(" ");
}


// Add active class to the current button (highlight it)
var btnContainer = document.getElementById("myBtnContainer");
var btns = btnContainer.getElementsByClassName("btn");
for (var i = 0; i < btns.length; i++) {
  btns[i].addEventListener("click", function(){
    var current = document.getElementsByClassName("active");
    current[0].className = current[0].className.replace(" active", "");
    this.className += " active";
  });
}




</script>

</body>
</html>